### ISSUE TITLE
Latest PR Broke Other modules referencing this one

### ISSUE THREAD

**Issue by cbwells** [aztfmod/terraform-azurerm-caf-naming#6]
When I am trying to download other modules in the repo I am not getting this error

`Could not download module "caf_name_st" (module.tf:3) source code from
"git::https://github.com/aztfmod/terraform-azurerm-caf-naming?ref=v0.1.2":
error downloading
'https://github.com/aztfmod/terraform-azurerm-caf-naming?ref=v0.1.2':
C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into
'.terraform\modules\caf_name_st'...
error: invalid path 'examples/caf_naming_container_registry-cafrandom
/README.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

Possibly related to the folder examples/caf_naming_container_registry-cafrandom as I get this error message when trying to clone this repo (not sure if it has a unicode character or is actually a space at the end).

error: invalid path 'examples/caf_naming_container_registry-cafrandom /README.md'
error: invalid path 'examples/caf_naming_container_registry-cafrandom /acr.tf'
error: invalid path 'examples/caf_naming_container_registry-cafrandom /locals.tf'
error: invalid path 'examples/caf_naming_container_registry-cafrandom /output.tf'
Done

Seems to be only on Windows as running my task in an Linux environment did not throw an error.

**Comment by arnaudlh** [comment]
Can repro on Windows when cloning the module directly. 
It does not happen in the rover (the landing zone main deployment technique) nor on Linux/Mac.
Will fix in next 2001 iteration.

**Comment by arnaudlh** [comment]
Should be fixed in 0.1.3
