### ISSUE TITLE
cafrandom convention for rg giving double dash (--)

### ISSUE THREAD

**Issue by iriahk89** [aztfmod/terraform-azurerm-caf-naming#8]
![image](https://user-images.githubusercontent.com/19380966/73325398-57d8cc00-4289-11ea-81fd-f3f2911d3861.png)

<img width="383" alt="naming issue 2" src="https://user-images.githubusercontent.com/19380966/73325337-1fd18900-4289-11ea-8344-523b34a2e9a4.PNG">

![image](https://user-images.githubusercontent.com/19380966/73325376-42fc3880-4289-11ea-8341-13e0ec8adb98.png)

**Comment by arnaudlh** [comment]
Closing as changes merged earlier.
